In [3]:
x=5
x

5

In [6]:
import pandas as pd
play_data=pd.read_csv("Macintosh HD\Users\meghanasurya\Desktop\Homework1.csv")
play_data

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 12-13: truncated \UXXXXXXXX escape (<ipython-input-6-2b55da625955>, line 2)

In [67]:
import pandas as pd
play_data=pd.read_csv("/Users/meghanasurya/Desktop/Homework1.csv")
play_data

Example Crust Shape Crust Size Crust Shade Filling Size Filling shade Class
0      ex1      CIrcle      Thick        Gray        Thick          Dark   pos
1      ex2      CIrcle      Thick       White        Thick          Dark   pos
2      ex3    Triangle      Thick        Dark        Thick          Gray   pos
3      ex4      CIrcle       Thin       White         Thin          Dark   pos
4      ex5      Square      Thick        Dark         Thin         White   pos
5      ex6      CIrcle      Thick       White         Thin          Dark   pos
6      ex7      CIrcle      Thick        Gray        Thick         White   neg
7      ex8      Square      Thick       White        Thick          Gray   neg
8      ex9    Triangle       Thin        Gray         Thin          Dark   neg
9     ex10      CIrcle      Thick        Dark        Thick         White   neg
10    ex11      Square      Thick       White        Thick          Dark   neg
11    ex12    Triangle      Thick       White        Thick          Gray   neg

In [68]:
df=pd.get_dummies(play_data,columns=["Crust Shape","Filling Size","Class"])
df

Example Crust Size Crust Shade Filling shade  Crust Shape_CIrcle  \
0      ex1      Thick        Gray          Dark                   1   
1      ex2      Thick       White          Dark                   1   
2      ex3      Thick        Dark          Gray                   0   
3      ex4       Thin       White          Dark                   1   
4      ex5      Thick        Dark         White                   0   
5      ex6      Thick       White          Dark                   1   
6      ex7      Thick        Gray         White                   1   
7      ex8      Thick       White          Gray                   0   
8      ex9       Thin        Gray          Dark                   0   
9     ex10      Thick        Dark         White                   1   
10    ex11      Thick       White          Dark                   0   
11    ex12      Thick       White          Gray                   0   

    Crust Shape_Square  Crust Shape_Triangle  Filling Size_Thick  \
0                    0                     0                   1   
1                    0                     0                   1   
2                    0                     1                   1   
3                    0                     0                   0   
4                    1                     0                   0   
5                    0                     0                   0   
6                    0                     0                   1   
7                    1                     0                   1   
8                    0                     1                   0   
9                    0                     0                   1   
10                   1                     0                   1   
11                   0                     1                   1   

    Filling Size_Thin  Class_neg  Class_pos  
0                   0          0          1  
1                   0          0          1  
2                   0          0          1  
3                   1          0          1  
4                   1          0          1  
5                   1          0          1  
6                   0          1          0  
7                   0          1          0  
8                   1          1          0  
9                   0          1          0  
10                  0          1          0  
11                  0          1          0

In [43]:
X=df[["Crust Shape_CIrcle","Crust Shape_Square","Filling Size_Thin"]]
X

Crust Shape_CIrcle  Crust Shape_Square  Filling Size_Thin
0                    1                   0                  0
1                    1                   0                  0
2                    0                   0                  0
3                    1                   0                  1
4                    0                   1                  1
5                    1                   0                  1
6                    1                   0                  0
7                    0                   1                  0
8                    0                   0                  1
9                    1                   0                  0
10                   0                   1                  0
11                   0                   0                  0

In [41]:
i=df[["Class_pos"]]
i

Class_pos
0           1
1           1
2           1
3           1
4           1
5           1
6           0
7           0
8           0
9           0
10          0
11          0

In [69]:
j=df[["Filling shade"]]
j

Filling shade
0           Dark
1           Dark
2           Gray
3           Dark
4          White
5           Dark
6          White
7           Gray
8           Dark
9          White
10          Dark
11          Gray

In [37]:
o=df[["Filling Size_Thin"]]
o

Filling Size_Thin
0                   0
1                   0
2                   0
3                   1
4                   1
5                   1
6                   0
7                   0
8                   1
9                   0
10                  0
11                  0

In [44]:
import numpy as np
from sklearn.linear_model import LinearRegression
p=LinearRegression().fit(X,i)
p

LinearRegression()

In [45]:
LinearRegression()

LinearRegression()

In [46]:
p.coef_

array([[ 3.33333333e-01, -2.64801244e-17,  3.75000000e-01]])

In [47]:
p.intercept_

array([0.20833333])

In [48]:
np.array(X)

array([[1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 0]], dtype=uint8)

In [49]:
np.array(i)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=uint8)

In [50]:
p=LinearRegression()
p.fit(np.array(X),np.array(i))
p

LinearRegression()

In [51]:
p.coef_

array([[ 3.33333333e-01, -2.64801244e-17,  3.75000000e-01]])

In [52]:
p.predict(X)

array([[0.54166667],
       [0.54166667],
       [0.20833333],
       [0.91666667],
       [0.58333333],
       [0.91666667],
       [0.54166667],
       [0.20833333],
       [0.58333333],
       [0.54166667],
       [0.20833333],
       [0.20833333]])

In [53]:
i_outputs=i.copy()
p_outputs=[float(p.predict(np.reshape(row,(1,-1)))) for row in X.itertuples(index=False)]
predicted=np.array([1 if p_output>=0.5 else 0 for p_output in p_outputs])
i_outputs=i_outputs.assign(regression_predicted=i_outputs)
i_outputs=i_outputs.assign(predicted=predicted)
i_outputs["reg"]=p_outputs
i_outputs

Class_pos  regression_predicted  predicted       reg
0           1                     1          1  0.541667
1           1                     1          1  0.541667
2           1                     1          0  0.208333
3           1                     1          1  0.916667
4           1                     1          1  0.583333
5           1                     1          1  0.916667
6           0                     0          1  0.541667
7           0                     0          0  0.208333
8           0                     0          1  0.583333
9           0                     0          1  0.541667
10          0                     0          0  0.208333
11          0                     0          0  0.208333

In [54]:
np.array(i)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=uint8)

In [55]:
i_outputs=i.copy()
i_outputs.assign(predicted=predicted)

Class_pos  predicted
0           1          1
1           1          1
2           1          0
3           1          1
4           1          1
5           1          1
6           0          1
7           0          0
8           0          1
9           0          1
10          0          0
11          0          0